INSERT INTO e_notification_types ("value", "description") VALUES
    ('GameUpdate', 'GameUpdate'),
    ('MatchSupport', 'MatchSupport'),
    ('GameNodeStatus', 'GameNodeStatus'),
    ('NameChangeRequest', 'NameChangeRequest'),
    ('MatchAbandoned', 'A player abandoned a match'),
    ('NameChangeApproved', 'Your name change request was approved'),
    ('NameChangeDenied', 'Your name change request was denied'),
    ('DedicatedServerStatus', 'DedicatedServerStatus'),
    ('DedicatedServerRconStatus', 'DedicatedServerRconStatus'),
    ('MatchStatusChange', 'Match Status Change Notification'),
    ('StorageScan', 'Storage Scan'),
    ('PlayerSanctioned', 'A player you recently played with received a sanction'),
    ('ScrimRequestReceived', 'A team requested to scrim yours'),
    ('ScrimRequestCountered', 'A team proposed a different scrim time'),
    ('ScrimRequestAccepted', 'Your scrim request was accepted'),
    ('ScrimRequestDeclined', 'Your scrim request was declined'),
    ('ScrimRequestExpired', 'A scrim request expired without a response'),
    ('ScrimMatchScheduled', 'A scrim match has been scheduled'),
    ('ScrimMatchCanceled', 'A scheduled scrim match was canceled'),
    ('ScrimTimeChanged', 'A scheduled scrim time changed'),
    ('ScrimAlertMatch', 'A team matching your scrim alert is available'),
    ('FormTeamSuggestion', 'You frequently play with these players'),
    ('EloRecompute', 'Player ELO recompute finished'),
    ('PlayerReindex', 'Player search reindex finished'),
    ('LeagueProposalReceived', 'A league opponent proposed a match time'),
    ('LeagueProposalAccepted', 'Your league match time proposal was accepted'),
    ('LeagueProposalDeclined', 'Your league match time proposal was declined'),
    ('LeagueMatchUnscheduled', 'A league matchup is unscheduled and will default soon'),
    ('LeagueRegistrationDecision', 'Your league registration was reviewed'),
    ('LeagueRosterUndersized', 'Your league team no longer meets the minimum roster size'),
    ('ChatMessage', 'A new message in a chat you are part of'),
    ('MatchChatMessage', 'A new message in a match''s chat'),
    ('TournamentCreated', 'Registration opened for a tournament'),
    ('TournamentReminder', 'A tournament you are registered for starts soon'),
    ('TournamentCheckInOpen', 'Check-in has opened for a tournament you are registered for'),
    ('TournamentCheckInClosing', 'Check-in for your tournament closes soon'),
    ('TournamentCheckInMissed', 'Your team missed check-in and was not seeded'),
    ('NewsPublished', 'A news article was published'),
    ('TeamInvite', 'You were invited to a team'),
    ('TournamentTeamInvite', 'You were invited to play in a tournament'),
    ('TournamentInvite', 'You were invited to register for a tournament'),
    ('DraftInvite', 'You were invited to a draft lobby'),
    ('MatchStatsReady', 'Stats for a match you played are ready'),
    ('ClipReady', 'A clip you requested finished rendering'),
    ('AwardGranted', 'You received an award'),
    ('StorePurchasePaid', 'A store purchase was paid successfully'),
    ('StorePurchaseCancelled', 'A store purchase was cancelled or failed'),
    ('EventReminder', 'An event you are attending starts soon'),
    ('SeasonEnded', 'A season has ended'),
    ('UtilityPracticeInvite', 'You were invited to a utility practice session'),
    ('UtilityPracticeReady', 'Your utility practice server is ready'),
    ('UtilityDriftScanFinished', 'A utility drift scan finished'),
    ('TournamentPartySignup', 'Your lobby was signed up for a tournament as a free agent party')
ON CONFLICT("value") DO UPDATE
    SET "description" = EXCLUDED."description";
